hostname: mars 
mounts:
  - [LABEL=files0, /mnt/raw/0, ext4, ""]
  - [LABEL=files1, /mnt/raw/1, ext4, ""]
  - [LABEL=files2, /mnt/raw/2, ext4, ""]
runcmd:
  - [cp, -f, /mnt/config/rancher/.profile, /home/rancher/.profile]
  - [sudo, system-docker, exec, udev, udevadm, trigger]
write_files:
  - path: /etc/udev/rules.d/99-usb-serial.rules
    container: udev
    permissions: "0644"
    owner: root
    content: |
      SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", ATTRS{idProduct}=="7523", ATTRS{serial}=="0000:00:1d.0" SYMLINK="usbZigbee", OWNER="rancher", mode="0666"
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.1.20/24
        gateway: 192.168.1.1
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
      - 1.1.1.1
      - 1.0.0.1
  repositories:
    home-server:
        url: https://raw.githubusercontent.com/winterscar/home-server/master/rancher
  services_include:
    mergerfs: true
    update-config: true
    backup: true
    kernel-extras: true
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDa7CNcGtcEsdLVbYumNnq8PQZ8zzHVfaQ1UNXlk5opJZtOVxr49O5zHugkCISYscHJxIuq0zNk2v+a/qrg9EHj3rIMiO9p0CpsoZfLABz6k6S6LXgeqVrfZNp12MPc1PYeo7ZcEuV3btJuEVV6gk6qHsZi/kaV6xTM9/QForLL6SS9NaKNRwHEAyo5YfAkMsVJHCXGY4EN3Ae0UEYFazIBvDmPjasnPVkkIykpVnsULplSBQ14Zp10AI43lKLofAVgrrOw1/wA4OwIsUuGnQcy/CeWQuMxHATBUtK81GHDd6y6lkKivQPy0mMLwv1w2b1/tvbzKHD3NWICm5/zizVP/gfvvvB12OJ0eFfrZj0Nh/UPoXWM0x5jhZld/+lP2aapKWON9t7aCeXzlzoXRuSslyxz1S7r/7vnoR8Y8eSfBzXs1Vu4VKwUrlNBXWR0St60iMNTfout7X/HOTlb/IUNl7R6CjhiJE7X8QxjxgiYymHR6UJGurOPOjg6GC8mswF645xDy/3zkIZwDkkvg61dzGnWwb9anq0Kq6q/dskpS7Vi38DrvRBcabT1OyvIenqLz7ie74dXfaZwKBoJll0ZCZtLh5cz0ewW0uCghnTGAsSDhkjr5tc9sriJq0iEY7L0+vLV9sWDgfPBV6nNYapK3lOzevA75DS4HVfs5CIPtw==
  mathieu_pasquet