version : '3'

services:
  mergerfs:
    container_name: mergerfs
    volumes:
      - '~/config:/config'
      - '/mnt/A:/source1'
      - '/mnt/B:/source2'
      - '/mnt/C:/source3'
      - 'mnt/media:/mountpoint:shared'
    security_opt:
      - apparmor:unconfined
    cap_add:
      - CAP_SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      - 'ARGS=-o minfreespace=1K -o use_ino -o hard_remove -o category.create=mfs'
    image: hotio/mergerfs
  adguard:
    container_name: adguard
    restart: unless-stopped
    image: adguard/adguardhome
    volumes:
      - ${CONFIG_ROOT}/adguard/conf:/opt/adguardhome/conf
      - ${CONFIG_ROOT}/adguard/work:/opt/adguardhome/work
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "53:53"
      - "67:67/udp"
      - "68:68"
      - "853:853/tcp"
      - "3000:3000/tcp"
  unifi:
    container_name: unifi
    restart: unless-stopped
    image: jacobalberty/unifi
    volumes:
      - ${CONFIG_ROOT}/unifi:/unifi
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UNIFI_GID=${GROUP_ID}
      - UNIFI_UID=${USER_ID}
      - RUNAS_UID0=false
    network_mode: host
    expose:
      - "8443"
 #IOT
  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - ${CONFIG_ROOT}/mosquitto/config:/mosquitto/config
      - ${CONFIG_ROOT}/mosquitto/log:/mosquitto/log
      - ${CONFIG_ROOT}/mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1883:1883"
      - "9001:9001"
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    image: homeassistant/home-assistant
    network_mode: host
    depends_on:
      - mqtt
      - unifi
      - influxdb
    expose:
       - "8123"
    volumes:
      - ${CONFIG_ROOT}/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/hass/media:/media
  nodered:
    container_name: node-red
    restart: unless-stopped
    image: nodered/node-red-docker
    depends_on:
      - "home-assistant"
    user: root
    volumes:
      - ${CONFIG_ROOT}/node-red/data:/data
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "1880"
  influxdb:
    restart: unless-stopped
    container_name: influxdb
    image: influxdb:alpine
    volumes:
      - ${CONFIG_ROOT}/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/grocy:/config
    expose: 
      - "9283"
      - "80"
    restart: unless-stopped
# MEDIA
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PLEX_CLAIM=claim-wJ12UYvvaopGCCm1x7Wf
    network_mode: host
    volumes:
      - ${CONFIG_ROOT}/plex/config:/config
      - ${MOVIES_PATH}:/movies
      - ${TV_PATH}:/tv
      - ${MUSIC_PATH}:/music
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/radarr/config:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${MOVIES_PATH}:/movies
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sonarr/config:/config
      - ${TV_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "3579"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/ombi/config:/config
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/tautulli/config:/config
      - ${CONFIG_ROOT}/tautulli/logs:/logs:ro
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sabnzbd/config:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${INCOMPLETE_DL_PATH}:/incomplete-downloads
  nzbhydra:
    container_name: nzbhydra
    image: linuxserver/hydra2
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
    expose:
      - "5076"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/nzbhydra/config:/config