update-config:
  container_name: update-config
  restart: unless-stopped
  volumes:
    - /mnt/config:/config
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/rancher/cache:/config-cache
  environment:
    - WEBHOOK_SECRET='this is a test secret'
    - WEBHOOK_HOOKS_DIR=/config/update-config/hooks      
  ports:
    - '8000:8000'
  user: '1100:1101'
  image: winterscar/github-webhook