# Docker configuration backend
providers:
  docker:
    exposedbydefault: false
# API and dashboard configuration
api:
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    
defaultEntryPoints:
  - "http"
  - "https"

certificatesResolvers:
  letsencrypt:
    acme:
      email: mat@lets-encrypt.pasquet.co
      storage: acme.json
      httpChallenge:
        entryPoint: http