# Docker configuration backend
providers:
  docker:
    exposedbydefault: false
# API and dashboard configuration
api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: mat@lets-encrypt.pasquet.co
      storage: acme.json
      httpChallenge:
        entryPoint: http