
# -------- Corridor lights -------------------------------------------------------------------------
- alias: Turn on corridor light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_motion_occupancy
    to: 'on'
  action:
    service: script.turn_on_lights
    data:
      entity_id: light.corridor_lights

- alias: Turn off corridor light after movement
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_motion_occupancy
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.corridor_lights

# --------------------------------------------------------------------------------------------------

- alias: Set motion helper to false at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.helper_morning_covers_opened

- alias: Open covers in the morning
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_motion_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.helper_morning_covers_opened
      state: 'off'
  action:
    - service: cover.open_cover
      entity_id:
        - cover.kitchen_blind
        - cover.bedroom_curtain
        - cover.living_room_curtain
        - cover.office_blind
    - service: input_boolean.turn_on
      entity_id: input_boolean.helper_morning_covers_opened
  
- alias: Stop living room curtain if the door is open
  trigger:
    platform: state
    entity_id: cover.living_room_curtain
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_window_sensor_contact
      state: 'on'
  action:
    service: cover.stop_cover
    entity_id: cover.living_room_curtain

# Bedroom light controller automations
- alias: Bedroom Light Switch
  id: bedroom_light_switch
  mode: parallel
  trigger:
    platform: state
    entity_id: sensor.bedroom_light_switch_action
  action:
    choose:
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.bedroom_lights
              state: "off"
            - condition: state
              entity_id: sensor.bedroom_light_switch_action
              state: "toggle"
        sequence:
          service: script.turn_on_lights
          data:
            entity_id: light.bedroom_lights
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.bedroom_lights
              state: "on"
            - condition: state
              entity_id: sensor.bedroom_light_switch_action
              state: "toggle"
        sequence:
          service: light.turn_off
          entity_id: light.bedroom_lights

- alias: Living Room Light Switch
  id: living_room_light_switch
  mode: parallel
  trigger:
    platform: state
    entity_id: sensor.living_room_light_switch_action
  action:
    choose:
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.living_room_lights
              state: "off"
            - condition: state
              entity_id: sensor.living_room_light_switch_action
              state: "toggle"
        sequence:
          service: script.turn_on_lights
          data:
            entity_id: light.living_room_lights
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.living_room_lights
              state: "on"
            - condition: state
              entity_id: sensor.living_room_light_switch_action
              state: "toggle"
        sequence:
          service: light.turn_off
          entity_id: light.living_room_lights

- alias: Office Light Switch
  id: office_light_switch
  mode: parallel
  trigger:
    platform: state
    entity_id: sensor.office_light_switch_click
  action:
    choose:
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.office_light
              state: "off"
            - condition: state
              entity_id: sensor.office_light_switch_click
              state: "left"
        sequence:
          service: script.turn_on_lights
          data:
            entity_id: light.office_light
      - conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.office_light
              state: "on"
            - condition: state
              entity_id: sensor.office_light_switch_click
              state: "left"
        sequence:
          service: light.turn_off
          entity_id: light.office_light