
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.0.0.0/8

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  # ### PACKAGES ###############################
  packages:
    amplifier:     !include packages/amplifier.yaml
    projector:     !include packages/projector.yaml
    vacuum:        !include packages/vacuum-cleaner.yaml
    zigbee_groups: !include packages/zigbee_groups.yaml
    light_groups:  !include packages/light_groups.yaml
    mat_pc:        !include packages/mat_pc.yaml
    building_door: !include packages/apartment_buzzer.yaml
    modes:         !include packages/modes.yaml
  # ############################################

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

recorder:
  purge_keep_days: 1
  db_url: sqlite:////storage/history

wake_on_lan:

logger:
  default: info
  logs:
    custome_components.onkyo: debug
    pyeiscp.protocol: debug
    pyeiscp.connection: debug

media_extractor:

mqtt:
  discovery: true
  broker: mars
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

influxdb:
  host: mars

media_player:
  - platform: mpd
    host: mars
    port: 6602
    name: Media - Mat
  - platform: mpd
    host: mars
    port: 6601
    name: Media - Jessie
  - platform: mpd
    host: mars
    port: 6600
    name: Media - Guest
  - platform: snapcast
    host: mars
    port: 1705

light:
  - platform: nanoleaf
    host: 10.10.10.38
    token: 4ETtAAOkyAD57j1ePu4OJ3ICl2OOICQ4
    name: Bedroom Nanoleaf
  - platform: nanoleaf
    host: 10.10.10.17
    token: ySFGJ4VBb1WbuCJP7mCvNqH2ZABKHg4F
    name: Living Room Nanoleaf