
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: home.pasquet.co

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  # ### PACKAGES ###############################
  packages:
    amplifier:     !include packages/amplifier.yaml
    projector:     !include packages/projector.yaml
    vacuum:        !include packages/vacuum-cleaner.yaml
    circadian:     !include packages/circadian_lighting.yaml
    zigbee_groups: !include packages/zigbee_groups.yaml
    light_groups:  !include packages/light_groups.yaml
  # ############################################

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
  automation: !include automations.yaml

recorder:
  purge_keep_days: 1
  db_url: sqlite:////storage/history

logger:
  default: info
  logs:
    custome_components.onkyo: debug
    pyeiscp.protocol: debug
    pyeiscp.connection: debug

mqtt:
  discovery: true
  broker: mars
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

sensor:
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

influxdb:
  host: mars