
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: home.pasquet.co

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  # ### PACKAGES ###############################
  packages:
    amplifier: !include packages/amplifier.yaml
    projector: !include packages/projector.yaml
  # ############################################

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

recorder:
  purge_keep_days: 1

automation:
  - alias: 'Set theme at startup'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: synthwave
logger:
  default: info
  logs:
    custome_components.onkyo: debug
    pyeiscp.protocol: debug
    pyeiscp.connection: debug  


vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.23
    token: !secret roborock_token
