media_player:
  - platform: onkyo
    host: 10.10.10.22
    name: Amplifier
    max_volume: 75
    sources:
      tv: 'Chrome Cast'
      cd: 'Projector'
      video2: 'Switch'
      video3: 'Mats PC'
      strm-box: 'Music'

automation:
  - id: switch_source_to_mopidy
    alias: Change sources when mopidy starts playing
    trigger: 
      platform: state
      entity_id: 
        - media_player.media_mat
        - media_player.media_jessie
        - media_player.media_guest
      to: "playing"
    condition:
      - condition: and
        conditions:          
          - condition: template
            value_template: "{{ state_attr('media_player.amplifier', 'source') != 'Music' }}"
          - condition: template
            value_template: "{{  not(state_attr('media_player.livingroom_speaker', 'is_volume_muted')) }}"
          - condition: template
            value_template: >-
              {{  (trigger.entity_id == 'media_player.media_mat' and 
                    state_attr('media_player.livingroom_speaker', 'source') == 'Mat')
                or (trigger.entity_id == 'media_player.media_jessie' and
                    state_attr('media_player.livingroom_speaker', 'source') == 'Jessie')
                or (trigger.entity_id == 'media_player.media_guest' and
                    state_attr('media_player.livingroom_speaker', 'source') == 'Guest') }}
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.amplifier
      - service: media_player.select_source
        data:
          entity_id: media_player.amplifier
          source: Music
  - id: switch_source_snapcast
    alias: Change amplifier source if the livingroom speaker changes source
    trigger:
      - platform: state
        entity_id: media_player.livingroom_speaker
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.attributes.source != trigger.to_state.attributes.source }}"
    action:
      - service: media_player.turn_on
        data:
          entity_id: media_player.amplifier
      - service: media_player.select_source
        data:
          entity_id: media_player.amplifier
          source: Music