script:
  someone_at_building_door:
    alias: "Notify someone is at the building door"
    sequence:
    - service: media_player.play_media
      data:
        entity_id:
          - media_player.kitchen_speaker
          - media_player.office_speaker
          - media_player.bedroom_mini
          - media_player.living_room_speaker
        media_content_id: 'https://home.pasquet.co/local/sounds/chime.mp3'
        media_content_type: audio/mp3
    - service: notify.mobile_app_mat_s_phone
      data:
        message: "Someone's at the door!"
        data:
          actions:
            - action: "open_building_door" # The key you are sending for the event
              title: "Open door" # The button title
    - service: notify.mobile_app_winter_is_coming
      data:
        title: "Someone's at the door!"
        message: "There's someone at the building door. Tap 'Open Door' to let them in."
        data:
          push:
            category: "open_building_door"

input_boolean:
  buzzer_armed:
    name: Open buzzer on next press
    icon: mdi:bell-plus

ios:
  push:
    categories:
      - name: Open Building Door
        identifier: 'open_building_door'
        actions:
          - identifier: 'open_door'
            title: 'Open door'
            activationMode: 'background'
            authenticationRequired: true
            destructive: false
            behavior: 'default'

automation:
  - id: open_building_door_from_notification
    alias: "Open the building door from a notification"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: open_building_door
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: open_door
    action:
      - service: switch.turn_on
        entity_id: switch.building_access
  - id: notify_someone_at_building_door
    alias: "Notify that there's someone at the building door"
    mode: single
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: binary_sensor.buzzer
      to: 'on'
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.buzzer_armed
              state: 'on'
          sequence:
            - service: input_boolean.turn_off
              entity_id: input_boolean.buzzer_armed
            - service: switch.turn_on
              entity_id: switch.building_access
        default:
          - service: script.someone_at_building_door
          - delay:
              seconds: 25
  - id: arm_buzzer_when_we_arrive_home
    alias: Arm the buzzer when we arrive home
    trigger:
      - platform: state
        entity_id: person.mathieu_pasquet
        to:  'home'
      - platform: state
        entity_id: person.jessie_scotson
        to:  'home'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.buzzer_armed
      - delay:
          minutes: 2