binary_sensor:
  - platform: mqtt
    name: "mats_pc_power"
    state_topic: "iotlink/workgroup/earth/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1


switch:
  - platform: template
    switches:
      mats_pc:
        friendly_name: "Mat's PC"
        value_template: "{{ is_state('binary_sensor.mats_pc_power', 'on') }}"
        turn_on:
          service: script.mat_pc_wake
        turn_off:
          service: script.mat_pc_shutdown
        icon_template: mdi:laptop

script:
  mat_pc_wake:
    # To enable see https://www.home-assistant.io/components/wake_on_lan/
    alias: "Mat's PC - Wake"
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "40-8d-5c-51-90-8d"
  mat_pc_shutdown:
    alias: "Mat's PC - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/earth/commands/shutdown"
          payload: ""
